[package]
name = "boa_alignment_test"
version = "0.1.0"
edition = "2021"

[dependencies]
boa_engine = { git = "https://github.com/andreievg/boa.git" }

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "test_runner"
path = "src/main.rs"