name: Android ARM64 Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
      
    - name: Build ARM64 binary
      run: cross build --target aarch64-linux-android --release --config target.aarch64-linux-android.rustflags='["-C", "target-feature=+crt-static"]'
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - name: Install QEMU user-static
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-user-static

    - name: Run aarch64-linux-android binary
      run: |
        # Verify it's static
        file ./target/aarch64-linux-android/release/test_runner

        chmod +x ./target/aarch64-linux-android/release/test_runner
        
        # Run directly with QEMU - no Docker needed!
        qemu-aarch64-static ./target/aarch64-linux-android/release/test_runner